server:
  port: 8080
spring:
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftlh # springboot 2.xx 后缀为 ftlh
    cache: false
# 静态资源 js，css
  resources:
    static-locations: classpath:/static/
logging:
  level:
    root: info
elasticsearch:
  url: 47.96.41.209:9200
